(() => {
  const login=document.querySelector('[data-admin-login]'),app=document.querySelector('[data-admin-app]'),message=document.querySelector('[data-admin-message]');
  const statuses=WGH.statuses,labels=WGH.statusLabels;let batches=[],orders=[],customers=[],selectedBatch=null;
  const escape=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

  let adminBusyCount=0;
  function adminBusy(on){
    let el=document.querySelector('[data-admin-busy]');
    if(!el){el=document.createElement('div');el.className='admin-action-loader';el.dataset.adminBusy='';el.innerHTML='<span class=\"page-spinner\"></span><small>Updating</small>';document.body.appendChild(el);}
    adminBusyCount=Math.max(0,adminBusyCount+(on?1:-1));el.classList.toggle('show',adminBusyCount>0);
  }
  async function adminApi(path,body){adminBusy(true);try{return await WGH.api(`/admin${path}`,body,{auth:true})}finally{adminBusy(false)}}
  function showView(name){document.querySelectorAll('[data-admin-view]').forEach(b=>b.classList.toggle('active',b.dataset.adminView===name));document.querySelectorAll('[data-view-panel]').forEach(p=>{const active=p.dataset.viewPanel===name;p.hidden=!active;p.classList.toggle('active',active)});document.body.classList.remove('admin-menu-open');window.scrollTo({top:0,behavior:'instant'});if(name==='overview')loadOverview();if(name==='orders')loadOrders();if(name==='customers')loadCustomers();if(name==='batches')loadBatches();}
  document.querySelectorAll('[data-admin-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.adminView)));document.querySelectorAll('[data-jump-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.jumpView)));document.querySelector('[data-admin-menu]')?.addEventListener('click',()=>document.body.classList.toggle('admin-menu-open'));

  async function waitForAuth(){if(!WGH.auth){setTimeout(waitForAuth,120);return;}WGH.auth.onAuthStateChanged(async user=>{if(!user){login.hidden=false;app.hidden=true;return;}try{await loadOverview();login.hidden=true;app.hidden=false;message.textContent='';}catch(err){message.textContent=WGH.friendlyError(err);await WGH.auth.signOut();}})}

  document.querySelector('[data-admin-login-form]')?.addEventListener('submit',async e=>{e.preventDefault();const btn=e.currentTarget.querySelector('button[type="submit"]'),data=Object.fromEntries(new FormData(e.currentTarget));message.textContent='';await WGH.withLoading(btn,async()=>{try{await WGH.auth.signInWithEmailAndPassword(data.email.trim(),data.password)}catch(err){message.textContent=WGH.friendlyError(err)}},'Signing in')});
  document.querySelector('[data-admin-signout]')?.addEventListener('click',e=>WGH.withLoading(e.currentTarget,()=>WGH.auth?.signOut(),'Signing out'));

  async function loadOverview(){
    const [overview,recentBatches,recentOrders]=await Promise.all([adminApi('/overview'),adminApi('/batches'),adminApi('/orders-all')]);batches=recentBatches;orders=recentOrders;
    document.querySelector('[data-overview-metrics]').innerHTML=[['Total orders',overview.orders],['Active orders',overview.activeOrders],['Pieces ordered',overview.pieces],['Sales',WGH.money(overview.revenue)],['Customers',overview.customers],['Production batches',overview.batches]].map(([l,v],i)=>`<article class="admin-metric"><span>0${i+1}</span><p>${l}</p><strong>${v}</strong></article>`).join('');
    document.querySelector('[data-overview-batches]').innerHTML=batches.slice(0,5).map(batchRow).join('')||empty('No production batches yet','Paid orders will create weekly batches automatically.');
    document.querySelector('[data-overview-orders]').innerHTML=orders.slice(0,6).map(orderRow).join('')||empty('No orders yet','New paid orders will appear here.');
  }
  const empty=(title,copy)=>`<div class="admin-empty compact"><h3>${title}</h3><p>${copy}</p></div>`;
  const batchRow=b=>{const pct=Math.min(100,Math.round(Number(b.usedCapacity||0)/Math.max(1,Number(b.capacity||1))*100));return `<button class="admin-batch-row" data-open-batch="${escape(b.id)}"><div><span>${escape(b.status||'OPEN')}</span><strong>${escape(b.batchName||b.id)}</strong></div><div class="batch-mini-cap"><span>${b.usedCapacity||0}/${b.capacity||0} pieces</span><i><b style="width:${pct}%"></b></i></div></button>`};
  const orderRow=o=>`<div class="admin-order-row"><div><strong>${escape(o.orderNumber)}</strong><span>${escape(o.customerName||o.customerEmail)}</span></div><div><span>${escape(o.batchName||'')}</span><strong>${labels[o.status]||'In progress'}</strong></div></div>`;

  async function loadBatches(){const btn=document.querySelector('[data-refresh-batches]');await WGH.withLoading(btn,async()=>{batches=await adminApi('/batches');renderBatchList();if(selectedBatch&&batches.some(b=>b.id===selectedBatch))await openBatch(selectedBatch)},'Refreshing')}
  function renderBatchList(){const list=document.querySelector('[data-batch-list]');list.innerHTML=`<div class="admin-card-head"><div><p class="eyebrow">Batches</p><h2>${batches.length} production cycles</h2></div></div>${batches.map(b=>batchRow(b).replace('admin-batch-row"','admin-batch-row '+(selectedBatch===b.id?'active':'')+'"')).join('')||empty('No batches yet','They will appear after the first paid order.')}`;list.querySelectorAll('[data-open-batch]').forEach(b=>b.addEventListener('click',()=>openBatch(b.dataset.openBatch)));}
  async function openBatch(id){selectedBatch=id;renderBatchList();const detail=document.querySelector('[data-batch-detail]');detail.innerHTML=`<div class="admin-loading"><span class="page-spinner"></span><p>Loading production sheet</p></div>`;try{const batch=batches.find(b=>b.id===id);const batchOrders=await adminApi(`/orders?batchId=${encodeURIComponent(id)}`);renderBatchDetail(batch,batchOrders)}catch(err){detail.innerHTML=empty('Could not load this batch',WGH.friendlyError(err))}}
  function aggregate(batchOrders){const map={};batchOrders.forEach(o=>(o.items||[]).forEach(item=>{const p=map[item.name]||(map[item.name]={total:0,colours:{}});p.total+=Number(item.totalQuantity||0);(item.variants||[]).forEach(v=>{p.colours[v.colour]=p.colours[v.colour]||{};p.colours[v.colour][v.size]=(p.colours[v.colour][v.size]||0)+Number(v.quantity||0)})}));return map}
  function renderBatchDetail(b,batchOrders){const detail=document.querySelector('[data-batch-detail]'),pct=Math.min(100,Math.round(Number(b.usedCapacity||0)/Math.max(1,Number(b.capacity||1))*100)),agg=aggregate(batchOrders);detail.innerHTML=`<div class="batch-detail-head"><div><p class="eyebrow">${escape(b.status||'OPEN')}</p><h2>${escape(b.batchName||b.id)}</h2><p>${date(b.startDate)} to ${date(b.closeDate)}</p></div><button class="button button-dark" data-export-batch>Download production sheet</button></div><div class="batch-capacity-large"><div><span>Capacity used</span><strong>${b.usedCapacity||0} / ${b.capacity||0} pieces</strong></div><span>${pct}%</span><i><b style="width:${pct}%"></b></i></div><div class="batch-stat-row"><div><span>Orders</span><strong>${batchOrders.length}</strong></div><div><span>Pieces</span><strong>${batchOrders.reduce((s,o)=>s+Number(o.pieces||0),0)}</strong></div><div><span>Styles</span><strong>${Object.keys(agg).length}</strong></div></div><div class="capacity-editor"><label>Maximum batch capacity<input type="number" min="1" value="${b.capacity||150}" data-capacity-input></label><button class="button button-outline" data-save-capacity>Save capacity</button></div><div class="production-breakdowns">${Object.entries(agg).map(([name,p])=>productionTable(name,p)).join('')||empty('No pieces in this batch','Orders assigned here will be summarised by colour and size.')}</div><div class="batch-orders-section"><div class="admin-card-head"><div><p class="eyebrow">Orders</p><h2>${batchOrders.length} orders in this batch</h2></div></div>${batchOrders.map(o=>orderAdminCard(o)).join('')||empty('No orders','')}</div>`;
    detail.querySelector('[data-save-capacity]')?.addEventListener('click',async e=>WGH.withLoading(e.currentTarget,async()=>{await adminApi('/capacity',{batchId:b.id,capacity:Number(detail.querySelector('[data-capacity-input]').value)});WGH.showToast('Batch capacity updated.','success');batches=await adminApi('/batches');renderBatchList();},'Saving'));
    detail.querySelector('[data-export-batch]')?.addEventListener('click',e=>{WGH.setLoading(e.currentTarget,true,'Preparing file');setTimeout(()=>{exportCsv(b,batchOrders);WGH.setLoading(e.currentTarget,false)},220)});
    bindStatus(detail,batchOrders);
  }
  function productionTable(name,p){const rows=[];Object.entries(p.colours).forEach(([colour,sizes])=>Object.entries(sizes).forEach(([size,qty])=>rows.push(`<tr><td>${escape(colour)}</td><td>${escape(size)}</td><td>${qty}</td></tr>`)));return `<section class="production-product"><div><h3>${escape(name)}</h3><strong>${p.total} pieces</strong></div><div class="admin-table-wrap"><table class="production-table"><thead><tr><th>Colour</th><th>Size</th><th>Quantity</th></tr></thead><tbody>${rows.join('')}</tbody></table></div></section>`}
  function orderAdminCard(o){return `<article class="batch-order-card"><div><strong>${escape(o.orderNumber)}</strong><span>${escape(o.customerName||o.customerEmail)}</span><small>${o.pieces} pieces · ${escape(o.estimatedDelivery)}</small></div><select data-status-order="${escape(o.orderNumber)}">${statuses.map(s=>`<option value="${s}" ${s===o.status?'selected':''}>${labels[s]}</option>`).join('')}</select></article>`}
  function bindStatus(root,source){root.querySelectorAll('[data-status-order]').forEach(select=>select.addEventListener('change',async()=>{select.disabled=true;const original=source.find(o=>o.orderNumber===select.dataset.statusOrder)?.status;try{await adminApi('/status',{orderNumber:select.dataset.statusOrder,status:select.value});WGH.showToast('Order stage updated and the customer will be notified.','success');const target=source.find(o=>o.orderNumber===select.dataset.statusOrder);if(target)target.status=select.value;}catch(err){select.value=original||select.value;WGH.showToast(err)}finally{select.disabled=false}}));}

  async function loadOrders(){const btn=document.querySelector('[data-refresh-orders]');await WGH.withLoading(btn,async()=>{orders=await adminApi('/orders-all');renderOrders()},'Refreshing')}
  function renderOrders(){const q=(document.querySelector('[data-order-search]').value||'').toLowerCase(),filter=document.querySelector('[data-order-filter]').value;const rows=orders.filter(o=>(filter==='all'||o.status===filter)&&`${o.orderNumber} ${o.customerName} ${o.customerEmail}`.toLowerCase().includes(q));document.querySelector('[data-orders-table]').innerHTML=rows.map(o=>`<tr><td><strong>${escape(o.orderNumber)}</strong></td><td>${escape(o.customerName)}<small>${escape(o.customerEmail)}</small></td><td>${escape(o.batchName)}</td><td>${o.pieces}</td><td>${WGH.money(o.total)}</td><td>${escape(o.estimatedDelivery)}</td><td><select data-status-order="${escape(o.orderNumber)}">${statuses.map(s=>`<option value="${s}" ${s===o.status?'selected':''}>${labels[s]}</option>`).join('')}</select></td></tr>`).join('')||`<tr><td colspan="7">No matching orders.</td></tr>`;document.querySelector('[data-orders-mobile]').innerHTML=rows.map(o=>`<article class="admin-mobile-card"><div><strong>${escape(o.orderNumber)}</strong><span>${escape(o.customerName)}</span></div><p>${o.pieces} pieces · ${WGH.money(o.total)} · ${escape(o.batchName)}</p><select data-status-order="${escape(o.orderNumber)}">${statuses.map(s=>`<option value="${s}" ${s===o.status?'selected':''}>${labels[s]}</option>`).join('')}</select></article>`).join('');bindStatus(document.querySelector('[data-view-panel="orders"]'),orders)}
  document.querySelector('[data-order-search]')?.addEventListener('input',renderOrders);document.querySelector('[data-order-filter]')?.addEventListener('change',renderOrders);

  async function loadCustomers(){const btn=document.querySelector('[data-refresh-customers]');await WGH.withLoading(btn,async()=>{customers=await adminApi('/customers');renderCustomers()},'Refreshing')}
  function renderCustomers(){document.querySelector('[data-customers-table]').innerHTML=customers.map(c=>`<tr><td><strong>${escape(c.name||'Customer')}</strong><small>${escape(c.email)}</small></td><td>${escape(c.phone)}</td><td>${c.orders}</td><td>${c.pieces}</td><td>${WGH.money(c.spent)}</td><td>${date(c.lastOrder)}</td></tr>`).join('')||`<tr><td colspan="6">No customer orders yet.</td></tr>`;document.querySelector('[data-customers-mobile]').innerHTML=customers.map(c=>`<article class="admin-mobile-card"><div><strong>${escape(c.name||'Customer')}</strong><span>${escape(c.email)}</span></div><p>${c.orders} orders · ${c.pieces} pieces · ${WGH.money(c.spent)}</p></article>`).join('')}
  const date=v=>v?new Date(v).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}):'—';
  function exportCsv(b,batchOrders){const lines=[['Batch','Order','Customer','Product','Colour','Size','Quantity']];batchOrders.forEach(o=>(o.items||[]).forEach(item=>(item.variants||[]).forEach(v=>lines.push([b.batchName,o.orderNumber,o.customerName,item.name,v.colour,v.size,v.quantity]))));const csv=lines.map(r=>r.map(x=>`"${String(x??'').replace(/"/g,'""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${(b.batchName||b.id).replace(/\s+/g,'-').toLowerCase()}-production-sheet.csv`;a.click();URL.revokeObjectURL(url)}

  document.querySelector('[data-refresh-overview]')?.addEventListener('click',e=>WGH.withLoading(e.currentTarget,loadOverview,'Refreshing'));document.querySelector('[data-refresh-batches]')?.addEventListener('click',loadBatches);document.querySelector('[data-refresh-orders]')?.addEventListener('click',loadOrders);document.querySelector('[data-refresh-customers]')?.addEventListener('click',loadCustomers);
  async function loadAnalytics(){if(!orders.length)orders=await adminApi('/orders-all');const revenue=orders.reduce((s,o)=>s+Number(o.total||0),0),pieces=orders.reduce((s,o)=>s+Number(o.pieces||0),0),avg=orders.length?revenue/orders.length:0;const metrics=document.querySelector('[data-analytics-metrics]');if(metrics)metrics.innerHTML=[['Revenue',WGH.money(revenue)],['Average order',WGH.money(avg)],['Pieces',pieces],['Orders',orders.length]].map(([l,v],i)=>`<article class="admin-metric"><span>0${i+1}</span><p>${l}</p><strong>${v}</strong></article>`).join('');const counts=Object.fromEntries(statuses.map(x=>[x,0]));orders.forEach(o=>counts[o.status]=(counts[o.status]||0)+1);const max=Math.max(1,...Object.values(counts));const bars=document.querySelector('[data-status-bars]');if(bars)bars.innerHTML=Object.entries(counts).filter(([,n])=>n).map(([k,n])=>`<div><span>${labels[k]||k}</span><i><b style="width:${n/max*100}%"></b></i><strong>${n}</strong></div>`).join('')||empty('No order data yet','Analytics will appear after the first order.');}
  async function loadAlerts(){if(!orders.length)orders=await adminApi('/orders-all');if(!batches.length)batches=await adminApi('/batches');const alerts=[];batches.forEach(b=>{const pct=Number(b.usedCapacity||0)/Math.max(1,Number(b.capacity||1));if(pct>=.8)alerts.push({icon:'fa-triangle-exclamation',title:`${b.batchName||b.id} is ${Math.round(pct*100)}% full`,copy:`${b.usedCapacity||0} of ${b.capacity||0} pieces are assigned.`})});orders.filter(o=>o.status==='quality_control').forEach(o=>alerts.push({icon:'fa-magnifying-glass',title:`${o.orderNumber} is in quality control`,copy:`${o.customerName||o.customerEmail} · ${o.pieces||0} pieces`}));orders.filter(o=>o.status==='ready_dispatch').forEach(o=>alerts.push({icon:'fa-truck-fast',title:`${o.orderNumber} is ready for dispatch`,copy:`Delivery estimate: ${o.estimatedDelivery||'Updating'}`}));const el=document.querySelector('[data-admin-alerts]');if(el)el.innerHTML=alerts.length?alerts.map(a=>`<article class="admin-notification"><i class="fa-solid ${a.icon}"></i><div><strong>${escape(a.title)}</strong><p>${escape(a.copy)}</p></div><span>Live</span></article>`).join(''):empty('Nothing needs attention','Production is running without generated alerts.');}
  async function loadSettings(){const settings=await adminApi('/settings');const el=document.querySelector('[data-admin-settings]');if(el)el.innerHTML=`<div class="setting-capacity"><label>Default pieces per production batch<input type="number" min="1" value="${Number(settings.batchCapacity||150)}" disabled></label><small>Per-batch capacity can be edited directly inside Production batches.</small></div>`;}
  document.querySelector('[data-refresh-analytics]')?.addEventListener('click',e=>WGH.withLoading(e.currentTarget,loadAnalytics,'Refreshing'));document.querySelector('[data-refresh-alerts]')?.addEventListener('click',e=>WGH.withLoading(e.currentTarget,loadAlerts,'Refreshing'));document.querySelector('[data-refresh-settings]')?.addEventListener('click',e=>WGH.withLoading(e.currentTarget,loadSettings,'Refreshing'));
  document.querySelector('[data-email-test-form]')?.addEventListener('submit',async e=>{e.preventDefault();const btn=e.currentTarget.querySelector('button'),msg=document.querySelector('[data-email-test-message]'),email=new FormData(e.currentTarget).get('email');msg.textContent='';await WGH.withLoading(btn,async()=>{try{const r=await adminApi('/email-test',{email});msg.textContent=`Email accepted by the delivery service${r.id?` · ${r.id}`:''}.`;}catch(err){msg.textContent=WGH.friendlyError(err)}},'Sending test')});
  document.querySelectorAll('[data-admin-view]').forEach(btn=>btn.addEventListener('click',()=>{const v=btn.dataset.adminView;if(v==='analytics')loadAnalytics();if(v==='alerts')loadAlerts();if(v==='settings')loadSettings();}));

  waitForAuth();
})();
