(() => {
  let cart=WGH.getCart(); if(!cart.length){location.replace('cart.html');return;}
  const subtotal=()=>cart.reduce((s,i)=>s+Number(i.unitPrice||0)*Number(i.totalQuantity||0),0), fee=()=>WGH.processingFee(subtotal()), total=()=>subtotal()+fee();
  const items=document.querySelector('[data-checkout-items]');
  function render(){items.innerHTML=cart.map(i=>`<article class="checkout-line-item"><img src="${i.image}" alt=""><div><strong>${i.name}</strong><span>${i.orderType} · ${i.totalQuantity} piece${i.totalQuantity===1?'':'s'}</span><small>${(i.variants||[]).map(v=>`${v.quantity}× ${v.colour} / ${v.size}`).join(' · ')}</small></div><b>${WGH.money(i.unitPrice*i.totalQuantity)}</b></article>`).join('');document.querySelector('[data-checkout-subtotal]').textContent=WGH.money(subtotal());document.querySelector('[data-checkout-fee]').textContent=WGH.money(fee());document.querySelector('[data-checkout-total]').textContent=WGH.money(total())}
  const now=new Date(),close=new Date(now);close.setDate(now.getDate()+((7-now.getDay())%7));const a=new Date(close),b=new Date(close);a.setDate(a.getDate()+14);b.setDate(b.getDate()+21);const fmt=d=>d.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});document.querySelector('[data-cycle-delivery]').textContent=`${fmt(a)} – ${fmt(b)}`;
  const fillEmail=()=>{const el=document.querySelector('[name="email"]');if(WGH.auth?.currentUser?.email&&!el.value)el.value=WGH.auth.currentUser.email};setTimeout(fillEmail,900);
  document.querySelector('[data-checkout-form]').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,btn=form.querySelector('button[type="submit"]'),data=Object.fromEntries(new FormData(form));await WGH.withLoading(btn,async()=>{try{const init=await WGH.api('/initialize-payment',{customer:{firstName:data.firstName,lastName:data.lastName,email:data.email,phone:data.phone,address:data.address,city:data.city,region:data.region},items:cart,madeToOrderAccepted:data.madeToOrderAccepted==='on'},{auth:!!WGH.auth?.currentUser});document.querySelector('[data-checkout-fee]').textContent=WGH.money(init.processingFee);document.querySelector('[data-checkout-total]').textContent=WGH.money(init.total);if(!window.PaystackPop)throw new Error('Secure payment did not load. Please refresh and try again.');new PaystackPop().newTransaction({key:init.publicKey,email:data.email,amount:init.amountKobo,reference:init.reference,currency:'GHS',onSuccess:async tx=>{WGH.setLoading(btn,true,'Confirming payment');try{const order=await WGH.api('/verify-payment',{reference:tx.reference});const record={...order,email:data.email,customer:{firstName:data.firstName,lastName:data.lastName,email:data.email,phone:data.phone,address:data.address,city:data.city,region:data.region},items:cart,status:order.status||'order_confirmed'};sessionStorage.setItem('wgh_last_order',JSON.stringify(record));const orders=JSON.parse(localStorage.getItem(WGH.ORDER_KEY)||'[]');orders.unshift(record);localStorage.setItem(WGH.ORDER_KEY,JSON.stringify(orders.slice(0,20)));WGH.saveCart([]);location.href='confirmation.html';}catch(err){WGH.showToast(err)}finally{WGH.setLoading(btn,false)}},onCancel:()=>WGH.showToast('Payment was not completed. Your bag is still saved.')});}catch(err){WGH.showToast(err)}},'Preparing payment')});render();
})();
