(()=>{let order=null;try{order=JSON.parse(sessionStorage.getItem('wgh_last_order')||'null')}catch{}if(!order){try{const list=JSON.parse(localStorage.getItem(WGH.ORDER_KEY)||'[]');const wanted=new URLSearchParams(location.search).get('order');order=list.find(o=>o.orderNumber===wanted)||list[0]}catch{}}if(!order){location.replace('shop.html');return;}const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const subtotal=Number(order.subtotal??(order.items||[]).reduce((s,i)=>s+Number(i.unitPrice||i.price||0)*Number(i.totalQuantity||i.quantity||1),0)),fee=Number(order.processingFee??WGH.processingFee(subtotal)),total=Number(order.total??subtotal+fee),c=order.customer||{};const q=s=>document.querySelector(s);q('[data-confirm-order]').textContent=order.orderNumber||'WGH —';q('[data-confirm-batch]').textContent=order.batchName||'Assigned soon';q('[data-confirm-delivery]').textContent=order.estimatedDelivery||'Updating soon';q('[data-track-confirm]').href=`tracking.html?order=${encodeURIComponent(order.orderNumber||'')}&email=${encodeURIComponent(c.email||order.email||'')}`;q('[data-receipt-order]').textContent=order.orderNumber||'WGH —';q('[data-receipt-date]').textContent=new Date().toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});q('[data-receipt-batch]').textContent=order.batchName||'Assigned soon';q('[data-receipt-delivery]').textContent=order.estimatedDelivery||'Updating soon';q('[data-receipt-code]').textContent=`${order.orderNumber||'WGH'} · ${String(c.email||order.email||'').toUpperCase()}`;q('[data-receipt-subtotal]').textContent=WGH.money(subtotal);q('[data-receipt-fee]').textContent=WGH.money(fee);q('[data-receipt-total]').textContent=WGH.money(total);q('[data-receipt-customer]').innerHTML=`<small>ORDER FOR</small><strong>${esc(`${c.firstName||''} ${c.lastName||''}`.trim()||'Customer')}</strong><span>${esc(c.fulfilment==='pickup'?'Pickup order':[c.address,c.city,c.region,c.country].filter(Boolean).join(' · '))}</span><span>${esc(c.email||order.email||'')}</span>`;q('[data-receipt-items]').innerHTML=(order.items||[]).map((i,n)=>`<div class="receipt-item"><div class="receipt-item-index">${n+1}</div><div><strong>${esc(i.name||'Item')}</strong><span>${esc(i.orderType||'made to order')} · ${Number(i.totalQuantity||1)} piece${Number(i.totalQuantity||1)===1?'':'s'}</span><small>${(i.variants||[]).map(v=>`${Number(v.quantity||0)}× ${esc(v.colour||v.color||'')} / ${esc(v.size||'')}`).join(' · ')}</small></div><b>${WGH.money(Number(i.unitPrice||i.price||0)*Number(i.totalQuantity||1))}</b></div>`).join('');
function pdf(download=true){if(!window.jspdf)return;const {jsPDF}=window.jspdf,d=new jsPDF({unit:'pt',format:'a4'}),x=54,w=487;d.setFillColor(20,18,17);d.rect(0,0,595,120,'F');d.setTextColor(255);d.setFont('helvetica','bold');d.setFontSize(18);d.text('THE WHOLESALE',x,52);d.text('GHANA',x,74);d.setFontSize(9);d.text('ORDER RECEIPT',x,98);d.setTextColor(20);d.setFontSize(25);d.text(order.orderNumber||'WGH',x,160);d.setFontSize(10);d.setFont('helvetica','normal');d.text(`Paid · ${new Date().toLocaleDateString('en-GB')}`,x,181);d.setDrawColor(215);d.line(x,200,x+w,200);let y=230;d.setFont('helvetica','bold');d.text(`${c.firstName||''} ${c.lastName||''}`.trim()||'Customer',x,y);d.setFont('helvetica','normal');y+=16;d.text(String(c.email||order.email||''),x,y);y+=34;(order.items||[]).forEach((i,idx)=>{d.setFont('helvetica','bold');d.text(`${idx+1}. ${String(i.name||'Item')}`,x,y);d.text(WGH.money(Number(i.unitPrice||i.price||0)*Number(i.totalQuantity||1)),x+w,y,{align:'right'});y+=15;d.setFont('helvetica','normal');d.setTextColor(95);d.text(`${i.orderType||'Made to order'} · ${i.totalQuantity||1} pieces`,x,y);y+=14;(i.variants||[]).forEach(v=>{d.text(`${v.quantity||0} × ${v.colour||v.color||''} / ${v.size||''}`,x+12,y);y+=13});d.setTextColor(20);y+=13;if(y>680){d.addPage();y=70}});d.line(x,y,x+w,y);y+=26;[['Subtotal',WGH.money(subtotal)],['Processing fee',WGH.money(fee)],['TOTAL PAID',WGH.money(total)]].forEach(([l,v],i)=>{d.setFont('helvetica',i===2?'bold':'normal');d.setFontSize(i===2?14:10);d.text(l,x,y);d.text(v,x+w,y,{align:'right'});y+=24});y+=12;d.setFillColor(244,240,234);d.roundedRect(x,y,w,72,4,4,'F');d.setFontSize(9);d.setFont('helvetica','bold');d.text('PRODUCTION JOURNEY',x+16,y+22);d.setFont('helvetica','normal');d.text(`${order.batchName||'Cycle assigned soon'} · Est. ${order.estimatedDelivery||'updating soon'}`,x+16,y+40);d.text('Made to order · Track every major stage from your account.',x+16,y+56);d.setFontSize(8);d.setTextColor(110);d.text('The Wholesale Ghana · Keep this receipt for your records.',x,810);return d}
function downloadReceipt(){
  const d=pdf(false);
  if(!d){WGH.showToast('Receipt generator is still loading. Please try again in a moment.');return false;}
  const blob=d.output('blob'),url=URL.createObjectURL(blob),a=document.createElement('a');
  a.href=url;a.download=`${order.orderNumber||'WGH'}-receipt.pdf`;a.style.display='none';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);return true;
}
function printReceipt(){
  document.body.classList.add('receipt-print-mode');
  const cleanup=()=>{document.body.classList.remove('receipt-print-mode');window.removeEventListener('afterprint',cleanup)};
  window.addEventListener('afterprint',cleanup);
  setTimeout(()=>window.print(),60);
}
const modal=q('[data-receipt-modal]');q('[data-view-receipt]').addEventListener('click',()=>{modal.hidden=false;document.body.classList.add('no-scroll')});document.querySelectorAll('[data-close-receipt]').forEach(b=>b.addEventListener('click',()=>{modal.hidden=true;document.body.classList.remove('no-scroll')}));q('[data-download-receipt]').addEventListener('click',downloadReceipt);
const key=`wgh_receipt_downloaded_${order.orderNumber||'latest'}`;
const printKey=`wgh_receipt_printed_${order.orderNumber||'latest'}`;
setTimeout(()=>{
  if(!localStorage.getItem(key)&&window.jspdf&&downloadReceipt())localStorage.setItem(key,'1');
},500);
setTimeout(()=>{
  if(!sessionStorage.getItem(printKey)){sessionStorage.setItem(printKey,'1');printReceipt();}
},1150);
})();
