(() => {
  let order=null;try{order=JSON.parse(sessionStorage.getItem('wgh_last_order')||'null')}catch{}
  if(!order){try{order=JSON.parse(localStorage.getItem(WGH.ORDER_KEY)||'[]')[0]}catch{}}
  if(!order){location.replace('shop.html');return;}
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const subtotal=Number(order.subtotal??(order.items||[]).reduce((s,i)=>s+Number(i.unitPrice||i.price||0)*Number(i.totalQuantity||i.quantity||1),0));
  const fee=Number(order.processingFee??WGH.processingFee(subtotal)); const total=Number(order.total??subtotal+fee);
  document.querySelector('[data-receipt-order]').textContent=order.orderNumber||'WGH —';document.querySelector('[data-receipt-date]').textContent=new Date().toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'});document.querySelector('[data-receipt-batch]').textContent=order.batchName||'Assigned soon';document.querySelector('[data-receipt-delivery]').textContent=order.estimatedDelivery||'Updating soon';document.querySelector('[data-receipt-code]').textContent=`${order.orderNumber||'WGH'} · ${String(order.email||order.customer?.email||'').toUpperCase()}`;document.querySelector('[data-receipt-subtotal]').textContent=WGH.money(subtotal);document.querySelector('[data-receipt-fee]').textContent=WGH.money(fee);document.querySelector('[data-receipt-total]').textContent=WGH.money(total);
  const c=order.customer||{};document.querySelector('[data-receipt-customer]').innerHTML=`<small>DELIVER TO</small><strong>${esc(`${c.firstName||''} ${c.lastName||''}`.trim()||'Customer')}</strong><span>${esc([c.address,c.city,c.region].filter(Boolean).join(' · '))}</span><span>${esc(c.email||order.email||'')}</span>`;
  document.querySelector('[data-receipt-items]').innerHTML=(order.items||[]).map((i,n)=>`<div class="receipt-item"><div class="receipt-item-index">${String(n+1).padStart(2,'0')}</div><div><strong>${esc(i.name||'Item')}</strong><span>${esc(i.orderType||'made to order')} · ${Number(i.totalQuantity||1)} piece${Number(i.totalQuantity||1)===1?'':'s'}</span><small>${(i.variants||[]).map(v=>`${Number(v.quantity||0)}× ${esc(v.colour||v.color||'')} / ${esc(v.size||'')}`).join(' · ')}</small></div><b>${WGH.money(Number(i.unitPrice||i.price||0)*Number(i.totalQuantity||1))}</b></div>`).join('');
  document.querySelector('[data-print-receipt]').addEventListener('click',()=>window.print());document.querySelector('[data-download-receipt]').addEventListener('click',()=>{const receipt=document.querySelector('[data-receipt]').outerHTML;const css='<style>body{font-family:Arial,sans-serif;background:#eee;padding:30px}.designer-receipt{max-width:620px;margin:auto;background:#fff;padding:38px;color:#171411}.designer-receipt header,.receipt-title,.receipt-meta,.receipt-item,.receipt-totals>div{display:flex;justify-content:space-between;gap:16px}.receipt-meta{padding:15px 0;border-top:1px solid #999;border-bottom:1px solid #999}.receipt-item{padding:14px 0;border-bottom:1px dashed #aaa}.receipt-customer{display:grid;gap:4px;padding:15px 0}.receipt-totals{padding:15px 0}.barcode{height:42px;background:repeating-linear-gradient(90deg,#111 0 2px,transparent 2px 5px);margin:20px 0}.receipt-tear{display:none}</style>';const blob=new Blob(['<!doctype html><meta charset=\"utf-8\"><title>Receipt '+(order.orderNumber||'WGH')+'</title>'+css+receipt],{type:'text/html'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(order.orderNumber||'WGH-order')+'-receipt.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),500)});
})();
